name: build

on:
  push:
    branches:
      - patched

jobs:
  build_patched_win:
    runs-on: windows-latest
    steps:
    - uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        expire-in: 0
    - uses: actions/checkout@v2
    - name: Cache node_modules
      uses: actions/cache@preview
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-projectname-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys:
          ${{ runner.os }}-projectname-
    - name: yarn install
      run: yarn install
    - name: yarn dist
      run: yarn dist
      working-directory: ./ElectronClient
    - name: Rename
      run: Dir | where { -Not $_.PsIscontainer -AND $_.name -match " " } | Rename-Item -NewName { $_.name -replace " ","_" }
      shell: powershell
      working-directory: ./ElectronClient/dist
    - name: ls
      run: ls
      working-directory: ./ElectronClient/dist
    - name: Upload artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: dist-win
        path: ./ElectronClient/dist/Joplin_Setup_*.exe
